language: python

services:
- docker

before_install:
- pip install black
- cp docker/test.conf docker/auth.conf
- docker-compose build
- docker-compose up -d

install:
- "export AUTH_PORT=$(docker-compose port auth 80 | cut -d: -f2)"

script:
- curl -L http://localhost:${AUTH_PORT}
- black --check --diff .

after_script:
- docker-compose down
